package auth

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/PawelHaracz/agentlens/internal/model"
)

func testUser() *model.User {
	return &model.User{
		ID:       "user-1",
		Username: "testuser",
		RoleID:   "role-admin",
		IsActive: true,
	}
}

func testRole() *model.Role {
	return &model.Role{
		ID:          "role-admin",
		Name:        "admin",
		Permissions: model.JSONSlice{"catalog:read", "catalog:write", "users:read"},
	}
}

func TestGenerateAndValidateToken(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:     "test-secret-key",
		Expiration: time.Hour,
	})

	user := testUser()
	role := testRole()

	token, err := svc.GenerateToken(user, role)
	require.NoError(t, err)
	assert.NotEmpty(t, token)

	claims, err := svc.ValidateToken(token)
	require.NoError(t, err)
	assert.Equal(t, "user-1", claims.UserID)
	assert.Equal(t, "testuser", claims.Username)
	assert.Equal(t, "role-admin", claims.RoleID)
	assert.Equal(t, []string{"catalog:read", "catalog:write", "users:read"}, claims.Permissions)
	assert.Equal(t, "agentlens", claims.Issuer)
}

func TestExpiredTokenIsRejected(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:     "test-secret-key",
		Expiration: -time.Hour, // already expired
	})

	token, err := svc.GenerateToken(testUser(), testRole())
	require.NoError(t, err)

	_, err = svc.ValidateToken(token)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "token")
}

func TestInvalidTokenIsRejected(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:     "test-secret-key",
		Expiration: time.Hour,
	})

	_, err := svc.ValidateToken("not-a-valid-token")
	assert.Error(t, err)
}

func TestWrongSecretIsRejected(t *testing.T) {
	svc1 := NewJWTService(JWTConfig{Secret: "secret-1", Expiration: time.Hour})
	svc2 := NewJWTService(JWTConfig{Secret: "secret-2", Expiration: time.Hour})

	token, err := svc1.GenerateToken(testUser(), testRole())
	require.NoError(t, err)

	_, err = svc2.ValidateToken(token)
	assert.Error(t, err)
}

func TestAutoGeneratedSecretWorks(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:     "", // should auto-generate
		Expiration: time.Hour,
	})

	token, err := svc.GenerateToken(testUser(), testRole())
	require.NoError(t, err)
	assert.NotEmpty(t, token)

	claims, err := svc.ValidateToken(token)
	require.NoError(t, err)
	assert.Equal(t, "user-1", claims.UserID)
}

func TestRefreshWindow(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:        "test-secret",
		Expiration:    time.Hour,
		RefreshWindow: 15 * time.Minute,
	})
	assert.Equal(t, 15*time.Minute, svc.RefreshWindow())
}

func TestRefreshWindowDefault(t *testing.T) {
	svc := NewJWTService(JWTConfig{
		Secret:     "test-secret",
		Expiration: time.Hour,
	})
	assert.Equal(t, 30*time.Minute, svc.RefreshWindow())
}
